#!/usr/bin/env bash
# .github/scripts/release-lib.sh
# Librería común para release pipeline
set -euo pipefail

# ---------------------
# Logging
# ---------------------
log()     { printf "▷ %s\n" "$*"; }
log_step(){ printf "▶ %s\n" "$*"; }
log_info(){ printf "ℹ %s\n" "$*"; }
log_warn(){ printf "⚠ %s\n" "$*"; }
log_err() { printf "❌ %s\n" "$*"; }

# ---------------------
# Safety helpers
# ---------------------
safe_cd() {
  local dir="$1"
  if [ -d "$dir" ]; then
    cd "$dir"
  else
    log_err "Directory does not exist: $dir"
    return 1
  fi
}

# ---------------------
# Framework config
# ---------------------
framework_config() {
  local key="$1"
  case "$key" in
    cam)
      PREFIX="${TAGPFX_CAM:-CameraSDK}"
      SCHEME="CameraSDK"
      PATHS="Libraries/Plugins/Camera/"
      VDIR="Sources/CameraSDK/Generated"
      EXTERNAL_REPO="lepsHub/PublicCameraSDK"
      POD_REPO="lepsHub/CameraSDK-pod"
      PODSPEC_NAME="sdk-camera.podspec"
      SPM_REPO="lepsHub/PublicCameraSDK"
      BINARY_NAME="CameraSDK"
      ;;
    core)
      PREFIX="${TAGPFX_CORE:-CoreSDK}"
      SCHEME="CoreSDK"
      PATHS="Libraries/External/Extended/App/"
      VDIR="Sources/CoreSDK/Generated"
      EXTERNAL_REPO="lepsHub/PublicCoreSDK"
      POD_REPO="lepsHub/CoreSDK-pod"
      PODSPEC_NAME="sdk-core.podspec"
      SPM_REPO="lepsHub/PublicCoreSDK"
      BINARY_NAME="CoreSDK"
      ;;
    *)
      log_err "Unknown framework key: $key"
      return 1
      ;;
  esac
  # export variables for convenience
  export PREFIX SCHEME PATHS VDIR EXTERNAL_REPO POD_REPO PODSPEC_NAME SPM_REPO BINARY_NAME
}

# ---------------------
# Plist helpers
# ---------------------
find_plists () { git ls-files "$1" | grep -E '/Info\.plist$' || true; }

read_short_ver () { /usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$1" 2>/dev/null || true; }

write_short_ver () {
  local file="$1" ver="$2"
  /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $ver" "$file" \
    || /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string $ver" "$file"
}

write_build_num () {
  local file="$1" bn="$2"
  /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $bn" "$file" \
    || /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $bn" "$file"
}

write_channel_key () {
  local file="$1" val="$2" key="${CHANNEL_PLIST_KEY:-TRVReleaseChannel}"
  /usr/libexec/PlistBuddy -c "Set :$key $val" "$file" \
    || /usr/libexec/PlistBuddy -c "Add :$key string $val" "$file"
}

# ---------------------
# Bump / version helpers
# ---------------------
bump_from_commits () {
  local last_prod="$1" range="$2" bump="patch"
  if git log --format=%B $range | grep -Eq 'BREAKING CHANGE|!:'; then bump="major"
  elif git log --format=%s $range | grep -Eq '^feat(\(|:)|^feat!'; then bump="minor"
  elif git log --format=%s $range | grep -Eq '^fix(\(|:)|^fix!|^perf(\(|:)|^perf!'; then bump="patch"
  else bump="patch"; fi

  if [ -z "$last_prod" ]; then
    echo "0.1.0"
    return
  fi

  base="${last_prod##*-}"
  IFS='.' read -r major minor patch <<< "$base"

  case "$bump" in
    major) major=$((major+1)); minor=0; patch=0 ;;
    minor) minor=$((minor+1)); patch=0 ;;
    patch) patch=$((patch+1)) ;;
  esac
  echo "${major}.${minor}.${patch}"
}

next_global_build_number() {
  local prefix="$1" base="$2" max=0
  while read -r t; do
    [ -z "$t" ] && continue
    n="${t##*.}"
    [[ "$n" =~ ^[0-9]+$ ]] && [ "$n" -gt "$max" ] && max="$n"
  done < <( git tag -l "${prefix}-${base}-BETA.*"; git tag -l "${prefix}-${base}-RC.*" )
  echo $((max + 1))
}

gen_version_swift () {
  local destdir="$1" full="$2" channel="$3" build="$4"
  mkdir -p "$destdir"
  cat > "$destdir/Version.swift" <<SWIFT
// Generated by CI – do not edit.
public let SDKVersionNumber: String = "$full"
public let SDKEnvironment:   String = "$channel"
public let SDKBuildNumber:   String = "$build"
SWIFT
}

gen_changelog_md () {
  local range="$1" path="$2"
  local feats fixes perfs refacs docs tests build ci chores breaks
  while IFS= read -r s; do
    [ -z "$s" ] && continue
    [[ "$s" =~ BREAKING\ CHANGE|!\: ]] && breaks="${breaks}"$'\n- '"$s"
    if   [[ "$s" =~ ^feat(\(|:|\!) ]];      then feats="${feats}"$'\n- '"$s"
    elif [[ "$s" =~ ^fix(\(|:|\!) ]];       then fixes="${fixes}"$'\n- '"$s"
    elif [[ "$s" =~ ^perf(\(|:|\!) ]];      then perfs="${perfs}"$'\n- '"$s"
    elif [[ "$s" =~ ^refactor(\(|:|\!) ]];  then refacs="${refacs}"$'\n- '"$s"
    elif [[ "$s" =~ ^docs(\(|:|\!) ]];      then docs="${docs}"$'\n- '"$s"
    elif [[ "$s" =~ ^test(\(|:|\!) ]];      then tests="${tests}"$'\n- '"$s"
    elif [[ "$s" =~ ^build(\(|:|\!) ]];     then build="${build}"$'\n- '"$s"
    elif [[ "$s" =~ ^ci(\(|:|\!) ]];        then ci="${ci}"$'\n- '"$s"
    elif [[ "$s" =~ ^chore(\(|:|\!) ]];     then chores="${chores}"$'\n- '"$s"
    fi
  done < <( git log --pretty=format:'%s' $range -- "$path" || true )

  {
    echo "## Changes"
    [ -n "$breaks" ] && { echo; echo "### ⚠️ Breaking Changes"; echo "$breaks"; }
    [ -n "$feats"  ] && { echo; echo "### ✨ Features";        echo "$feats"; }
    [ -n "$fixes"  ] && { echo; echo "### 🐛 Fixes";           echo "$fixes"; }
    [ -n "$perfs"  ] && { echo; echo "### 🚀 Performance";     echo "$perfs"; }
    [ -n "$refacs" ] && { echo; echo "### 🧹 Refactors";       echo "$refacs"; }
    [ -n "$docs"   ] && { echo; echo "### 📝 Docs";            echo "$docs"; }
    [ -n "$tests"  ] && { echo; echo "### ✅ Tests";           echo "$tests"; }
    [ -n "$build"  ] && { echo; echo "### 🧱 Build";           echo "$build"; }
    [ -n "$ci"     ] && { echo; echo "### ⚙️ CI";              echo "$ci"; }
    [ -n "$chores" ] && { echo; echo "### 🧰 Chore";           echo "$chores"; }
  } | sed '/^$/N;/^\n$/D' || true
}

# ---------------------
# Validation helpers
# ---------------------

# Validate that the .xcframework ZIP exists and is a valid zip containing an .xcframework
validate_xcframework_zip() {
  local zip_path="$1"
  if [ ! -f "$zip_path" ]; then
    log_err "XCFramework zip not found: $zip_path"
    return 1
  fi
  log_step "Checking zip integrity: $zip_path"
  if ! unzip -t "$zip_path" >/dev/null 2>&1; then
    log_err "Zip integrity check failed for $zip_path"
    return 1
  fi
  # ensure .xcframework exists inside zip
  if ! unzip -l "$zip_path" | grep -q '\.xcframework/'; then
    log_err "Zip does not contain an .xcframework: $zip_path"
    return 1
  fi
  log_info "Zip looks valid: $zip_path"
}

# Compute checksum using Swift package tool if available, otherwise sha256 fallback
compute_checksum() {
  local zipfile="$1"
  if command -v swift >/dev/null 2>&1; then
    swift package compute-checksum "$zipfile"
  else
    shasum -a 256 "$zipfile" | awk '{print $1}'
  fi
}

# Validate SPM package: compute checksum of zip and (optionally) compare with Package.swift if present
validate_spm_package() {
  local zipfile="$1"
  local tmpdir="${2:-/tmp/spm-validate}"
  mkdir -p "$tmpdir"
  log_step "Computing checksum for $zipfile"
  local cs
  cs=$(compute_checksum "$zipfile")
  log_info "Checksum: $cs"
  # If there's a Package.swift in current dir, try to ensure checksum is present in Package.swift
  if [ -f "Package.swift" ]; then
    if grep -q "$cs" Package.swift; then
      log_info "Package.swift contains the checksum"
    else
      log_warn "Calculated checksum not present in Package.swift (may be new release)"
    fi
  fi
  return 0
}

# Validate Podspec using pod lib lint (runs in the podrepo clone)
validate_podspec() {
  local podspec_path="$1"
  if [ ! -f "$podspec_path" ]; then
    log_err "Podspec not found: $podspec_path"
    return 1
  fi

  if ! command -v pod >/dev/null 2>&1; then
    log_warn "Pod command not found; installing CocoaPods (this may take a few minutes)..."
    sudo gem install cocoapods -v "> 1.11" || true
  fi

  log_step "Running pod lib lint for $podspec_path"
  # --allow-warnings to avoid failing on warnings; remove if you want strictness
  pod lib lint "$podspec_path" --allow-warnings --skip-tests --verbose
  rc=$?
  if [ $rc -ne 0 ]; then
    log_err "pod lib lint failed for $podspec_path"
    return $rc
  fi
  log_info "pod lib lint passed for $podspec_path"
  return 0
}

# ---------------------
# End of release-lib.sh
# ---------------------
