#!/usr/bin/env bash
set -euo pipefail

# env expected:
# CUT (beta|rc|prod), AFF (cam|core|cam core), TAGPFX_CAM, TAGPFX_CORE, GITHUB_WORKSPACE, CHANNEL_PLIST_KEY, DRY

cd "${GITHUB_WORKSPACE:-.}"

# Helpers
find_plists () { git ls-files "$1" | grep -E '/Info\.plist$' || true; }
read_short_ver () { /usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$1" 2>/dev/null || true; }
write_short_ver () { /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $2" "$1" || /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string $2" "$1"; }
write_build_num () { /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $2" "$1" || /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $2" "$1"; }
write_channel_key () {
  local plist="$1" val="$2" key="${CHANNEL_PLIST_KEY:-TRVReleaseChannel}"
  /usr/libexec/PlistBuddy -c "Set :$key $val" "$plist" \
    || /usr/libexec/PlistBuddy -c "Add :$key string $val" "$plist"
}

bump_from_commits () {
  local last_prod="$1" range="$2" bump="patch"
  if git log --format=%B $range | grep -Eq 'BREAKING CHANGE|!:'; then bump="major"
  elif git log --format=%s $range | grep -Eq '^feat(\(|:)|^feat!'; then bump="minor"
  elif git log --format=%s $range | grep -Eq '^fix(\(|:)|^fix!|^perf(\(|:)|^perf!'; then bump="patch"
  else bump="patch"; fi

  if [ -z "$last_prod" ]; then echo "0.1.0"; return; fi
  base="${last_prod##*-}"
  IFS='.' read -r major minor patch <<< "$base"
  case "$bump" in
    major) major=$((major+1)); minor=0; patch=0 ;;
    minor) minor=$((minor+1)); patch=0 ;;
    patch) patch=$((patch+1)) ;;
  esac
  echo "${major}.${minor}.${patch}"
}

gen_changelog_md () {
  local range="$1" path="$2"
  local out=""
  while IFS= read -r s; do
    [ -z "$s" ] && continue
    out="${out}"$'\n- '"$s"
  done < <(git log --pretty=format:'%s' $range -- "$path" || true)
  echo "${out}"
}

# Process each framework in AFF
for key in ${AFF// / }; do
  if [ "$key" = "cam" ]; then
    prefix="${TAGPFX_CAM:-CameraSDK}"
    path="Libraries/Plugins/Camera/"
    vdir="Sources/TruvideoSdkCamera/Generated"
  else
    prefix="${TAGPFX_CORE:-CoreSDK}"
    path="Libraries/External/Extended/App/"
    vdir="Sources/TruvideoSdk/Generated"
  fi

  last_prod=$(
    git tag -l "${prefix}-*" --sort=-v:refname \
    | grep -E "^${prefix}-[0-9]+\.[0-9]+\.[0-9]+$" \
    | head -n1
  )

  since_ref=""; [ -n "$last_prod" ] && since_ref="$(git rev-list -n1 "$last_prod")"
  range="${since_ref:+${since_ref}..}HEAD"

  base_ver="$(bump_from_commits "$last_prod" "${range:-HEAD}")"

  if [ "$CUT" = "beta" ]; then
    channel="BETA"
    # find next global build number
    build_num="$( (git tag -l "${prefix}-${base_ver}-BETA.*" || true) | awk -F. '{print $NF}' | sort -n | tail -n1 || true)"
    build_num=$(( ${build_num:-0} + 1 ))
    full="${base_ver}-BETA.${build_num}"
    prerelease="true"
    title="Internal BETA release for ${prefix} ${base_ver}."
  elif [ "$CUT" = "rc" ]; then
    channel="RC"
    build_num="$( (git tag -l "${prefix}-${base_ver}-RC.*" || true) | awk -F. '{print $NF}' | sort -n | tail -n1 || true)"
    build_num=$(( ${build_num:-0} + 1 ))
    full="${base_ver}-RC.${build_num}"
    prerelease="true"
    title="Release Candidate for ${prefix} ${base_ver}."
  else
    channel="PROD"
    full="${base_ver}"
    bn="$( (git tag -l "${prefix}-${base_ver}" || true) | wc -l )"
    [ "$bn" -gt 0 ] && build_num="$bn" || build_num="1"
    prerelease="false"
    title="Production release for ${prefix} ${base_ver}."
  fi

  # Update plists
  while read -r plist; do
    [ -z "$plist" ] && continue
    cur_short="$(read_short_ver "$plist")"
    if [ "$cur_short" != "$base_ver" ]; then write_short_ver "$plist" "$base_ver"; fi
    write_build_num "$plist" "$build_num"
    write_channel_key "$plist" "$channel"
  done < <(find_plists "$path")

  mkdir -p "$vdir"
  cat > "$vdir/Version.swift" <<SWIFT
// Generated by CI – do not edit.
public let SDKVersionNumber: String = "${full}"
public let SDKEnvironment:   String = "${channel}"
public let SDKBuildNumber:   String = "${build_num}"
SWIFT

  chg="$(gen_changelog_md "$range" "$path")"
  # store artifacts for later steps via files
  printf "%s\n" "${prefix}" > ".release_${key}_prefix"
  printf "%s\n" "${full}"   > ".release_${key}_full"
  printf "%s\n" "${build_num}" > ".release_${key}_build"
  printf "%s\n" "${prerelease}" > ".release_${key}_prerelease"
  printf "%s\n" "${title}" > ".release_${key}_title"
  printf "%s\n" "${chg}" > ".release_${key}_changelog"
done

echo "Versioning done. Release metadata written to .release_* files"
